### ISSUE TITLE
Help with bettertt

### ISSUE THREAD

**Issue by mjperrone** [platz1de/territorial-discord-bot#1]
Sorry to use the wrong medium for this, but I'm a big fan of BetterTT, and I have been missing it while it is incompatible with the latest version of the game.

If there's any way you can allow the community to help you support it, please let us know. I'm sure there are more than a few devs like myself who would be willing to help.

**Comment by platz1de** [comment]
I sadly can't open-source the project as it heavely depends on the main game.
There were already some close calls of the Creator almost shutting down BetterTT in the past, so he wouldn't accept publicising scripts which pretty much deobfucate his game.

**Comment by mjperrone** [comment]
Thanks for the context, and thanks for the great mod!
